[package]
name = "eme"
version = "0.1.0"
authors = ["Cody P Schafer <dev@codyps.com>"]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/jmesmon/eme"

[dependencies]
aesti = { optional = false, version = "*" }
index-fixed = "*"

[dev-dependencies]
fmt-extra = "*"
